query Characters {
    characters {
        edges {
            node {
                id
                created
                modified
                name
                description
                thumbUrl,
            }
        }
    }
}